# Gerardo de Miguel González

## M1967: NumPy: creating and manipulating numerical data

### Ejercicios Seguimiento Numpy II

Crea un Jupyter Notebook con cada ejercicio en su propia sección.

In [0]:
import numpy as np

#### Ejercicio 1

 Form the 2-D array (without typing it in explicitly):
 
<pre> [[1,  6, 11], 
 [2,  7, 12], 
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]</pre>
 
 and generate a new array containing its 2nd and 4th rows.

In [3]:
#::GMG::Primero creamos un array 1D con los elementos que vamos a colocar 
#       en el array 2D.
x = np.arange(1,16,1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [0]:
#::GMG::El objetivo es tener un array 2D de 5 filas y tres columnas.
#       Podríamos pensar en "darle forma" con reshape()
#np.reshape(x, (-1, 3))
y = x.reshape(5,3)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [0]:
#::GMG::El resultado no es el esperado ya que los elementos no están colocados
#       en el orden pedido. Tenemos que pensar tal vez en "slicing" ...
#       ... por ejemplo la filas se obtienen de la siguiente manera
display((x[::5],x[1::5],'...',x[4::5]))

(array([ 1,  6, 11]), array([ 2,  7, 12]), '...', array([ 5, 10, 15]))

In [4]:
#::GMG::Así que empleando "slicing" podemos construir el array 2D por
#       partes :)
y = np.array([x[::5],x[1::5],x[2::5],x[3::5],x[4::5]])
print(y)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [0]:
#::GMG::También podemos pensar en colocar los elementos como filas en 2D y 
#       luego tansponer el array 2D
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.transpose.html
y = np.transpose(x.reshape(3,5))
print(y)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [0]:
#::GMG::Otra alternativa es dividir el array 1D en tres partes y colocarlos
#       como columnas en el nuevo array 2D
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.column_stack.html
z = np.column_stack(np.split(x,3))
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#### Ejercicio 2

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.
     
Hints: 

- Use abs and argsort to find the column j closest for each row.
-  Use fancy indexing to extract the numbers.

In [0]:
np.random.seed(1)
r = np.random.rand(30).reshape(10,3)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01],
       [1.40386939e-01, 1.98101489e-01, 8.00744569e-01],
       [9.68261576e-01, 3.13424178e-01, 6.92322616e-01],
       [8.76389152e-01, 8.94606664e-01, 8.50442114e-02],
       [3.90547832e-02, 1.69830420e-01, 8.78142503e-01]])